import type {GameController,AppSnapshot} from './controller';
import type {GameState,GameView,Preview,Action,ActionOption,ScenarioId,Mode} from '../core/types';
import {readSave,parseSave,type SaveFile} from './storage';
import {sliceRound} from '../world/economy';
type Reply={notice?:string;exported?:string;options?:ActionOption[];view?:GameView;preview?:Preview;checksum?:string};
const escape=(s:unknown)=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function download(name:string,body:string,type='application/json'){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function createController():GameController{
 const worker=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});
 let id=0,revision=0,currentChecksum='';let saveQueue:Promise<void>=Promise.resolve();
 let snap:AppSnapshot={view:null,busy:false,error:null,pending:[],preview:null,notice:null,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,sound:false};
 const listeners=new Set<()=>void>();const calls=new Map<number,{resolve:(r:Reply)=>void;reject:(e:Error)=>void}>();
 const publish=(patch:Partial<AppSnapshot>)=>{snap={...snap,...patch};listeners.forEach(fn=>fn());};
 worker.onmessage=e=>{const c=calls.get(e.data.id);if(!c)return;calls.delete(e.data.id);e.data.error?c.reject(new Error(e.data.error)):c.resolve(e.data.result);};
 worker.onerror=e=>{publish({error:'The simulation stopped unexpectedly. Reload your last save to continue.',busy:false});calls.forEach(c=>c.reject(new Error(e.message)));calls.clear();};
 const request=(type:string,payload?:unknown):Promise<Reply>=>new Promise((resolve,reject)=>{const n=++id;calls.set(n,{resolve,reject});worker.postMessage({id:n,type,payload});});
 const capture=()=>({checksum:currentChecksum,pending:snap.pending});
 const persist=(save:Pick<SaveFile,'checksum'|'pending'>,key='autosave')=>{const next=saveQueue.catch(()=>{}).then(async()=>{await request('persist',{pending:save.pending,expected:save.checksum,key});});saveQueue=next;return next;};
 const autosave=async()=>{if(snap.view)try{await persist(capture());}catch{publish({notice:'Browser storage is unavailable. Export a save to keep this campaign.'});}};
 const apply=(r:Reply)=>{if(r.notice)publish({notice:r.notice});if(r.checksum)currentChecksum=r.checksum;if(r.view)publish({view:r.view});};
 const attempt=async(fn:()=>Promise<void>)=>{if(snap.busy)return;publish({busy:true,error:null,notice:null});try{await fn();}catch(e){publish({error:e instanceof Error?e.message:String(e)});}finally{publish({busy:false});}};
 const updatePreview=async()=>{const version=++revision;if(!snap.view)return;try{const r=await request('preview',snap.pending);if(version===revision)publish({preview:r.preview??null,...(r.options&&snap.view?{view:{...snap.view,options:r.options}}:{})});}catch(e){if(version===revision)publish({error:String(e)});}};
 const pulse=()=>{if(!snap.sound)return;try{const audio=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(430,audio.currentTime);o.frequency.exponentialRampToValueAtTime(650,audio.currentTime+.1);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.25);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.25);o.onended=()=>void audio.close();}catch{}}
 const step=async()=>{apply(await request('advance'));await autosave();};
 const year=async()=>{for(let n=0;n<4&&snap.view?.state.phase==='resolving';n++){await step();if(!snap.reducedMotion)await new Promise(r=>setTimeout(r,180));}pulse();};
 const controller:GameController={
  subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);},getSnapshot:()=>snap,
  newGame:(scenario:ScenarioId,seed:number,mode:Mode)=>attempt(async()=>{apply(await request('new',{scenario,seed,mode}));publish({pending:[],preview:null});revision++;await autosave();}),
  addAction:(action:Action)=>{if(snap.busy||snap.pending.length>=2||snap.view?.state.phase!=='planning')return;publish({pending:[...snap.pending,action],preview:null,error:null});void updatePreview();void autosave();},
  removeAction:index=>{if(snap.busy)return;publish({pending:snap.pending.filter((_,i)=>i!==index),preview:null,error:null});void updatePreview();void autosave();},
  commit:()=>attempt(async()=>{apply(await request('commit',snap.pending));publish({pending:[],preview:null});revision++;await autosave();await year();}),
  advance:()=>attempt(step),advanceYear:()=>attempt(year),
  delegateToNextStop:()=>attempt(async()=>{if(snap.pending.length)throw new Error('Commit or remove your planned actions before delegating.');apply(await request('delegate'));await autosave();pulse();}),
  save:()=>attempt(async()=>{if(!snap.view)throw new Error('Start a campaign first.');await persist(capture(),'manual');publish({notice:'Campaign saved in this browser.'});}),
  load:()=>attempt(async()=>{await saveQueue.catch(()=>{});const save=await readSave()??await readSave('manual');if(!save)throw new Error('No saved campaign found in this browser.');apply(await request('load',parseSave(save)));publish({pending:save.pending,preview:null,notice:'Campaign restored.'});await updatePreview();}),
  exportSave:()=>{void attempt(async()=>{if(!snap.view)return;const result=await request('export',{pending:snap.pending});if(result.exported)download(`healthspan-${snap.view.state.year}-${snap.view.state.seed}.json`,result.exported);});},
  importSave:file=>attempt(async()=>{if(file.size>25*1024*1024)throw new Error('This file is too large to be a campaign save.');const save=parseSave(JSON.parse(await file.text()));apply(await request('load',save));publish({pending:save.pending,preview:null,notice:'Campaign imported.'});await updatePreview();await autosave();}),
  setMode:mode=>{void attempt(async()=>{apply(await request('mode',mode));await autosave();});},
  setReducedMotion:enabled=>publish({reducedMotion:enabled}),setSound:enabled=>publish({sound:enabled}),
  downloadDebrief:(roundId,check)=>{const s=snap.view?.state;if(!s)return;const value=snap.view!.value;const pos=roundId?sliceRound(s,roundId,check,0,value):null;const usd=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n/100);const num=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);
   download(`healthspan-debrief-${s.seed}.html`,`<!doctype html><html lang="en"><meta charset="utf-8"><title>Healthspan · Your campaign</title><style>body{font:17px/1.55 system-ui;background:#f5f3eb;color:#153f3d;max-width:900px;margin:60px auto;padding:25px}h1{font-size:44px;line-height:1.05}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}article{border-top:1px solid #9ab6ac;padding:18px 0}b{font-size:26px}small{font-size:13px}button{padding:12px}@page{size:A4;margin:12mm}@media print{button{display:none}body{margin:0;padding:0;max-width:none;font-size:11px;line-height:1.35}h1{font-size:30px;margin:10px 0}h2{font-size:17px;margin:12px 0 6px}article{padding:9px 0}b{font-size:21px}p{margin:6px 0}.grid{gap:10px}small{font-size:10px}}</style><small>DIGITAL BIOLOGICS · ILLUSTRATIVE GAME OUTCOME</small><h1>The future you made deliverable.</h1><p>${escape(s.year)} · ${escape(s.scenario)} · Seed ${s.seed} · ${escape(s.status)}</p><div class="grid"><article>Expected net healthspan<br><b>${num(s.score.expected)} years</b><br>${num(s.score.experienced)} experienced · ${num(s.score.remaining)} expected remaining</article><article>Modeled equity value<br><b>${usd(value.equity)}</b><br>${usd(value.low)}–${usd(value.high)} scenario range</article><article>Your illustrative investment<br><b>${pos?usd(pos.check):'No round selected'}</b><br>${pos?(pos.ownership*100).toFixed(2)+'% after dilution':''}</article><article>Hypothetical proceeds<br><b>${pos?usd(pos.proceeds):'—'}</b><br>${pos?pos.multiple.toFixed(2)+'× investment':''}</article></div><h2>What changed the opportunity</h2>${[s.events.find(e=>e.major&&e.kind==='finance'),s.events.find(e=>e.major&&e.kind==='clinical'),...s.events.filter(e=>e.major&&e.kind==='policy').slice(-2),s.events.filter(e=>e.major&&e.kind==='network').at(-1)].filter((e):e is NonNullable<typeof e>=>!!e).sort((a,b)=>a.year-b.year||a.quarter-b.quarter).map(e=>`<p><strong>${e.year} · ${escape(e.title)}</strong><br>${escape(e.detail)}</p>`).join('')}<h2>Assumptions</h2><p>Aligned AI, fictional therapies and institutions, independently assessed expected benefits, improving alternative care. Corporate value uses five forecast years, 15% discount and an 8× recurring cash-flow residual. Investor payouts use 1× non-participating pari-passu preferences and a fully issued, vested option pool with zero exercise cost. Values are simulated, not actual Digital Biologics terms or forecasts.</p><p>Build ${escape(s.engineVersion)} / ${escape(s.contentVersion)} · ${num(s.score.people)} initiated recipients · control ${escape(s.company.control)}</p><button onclick="print()">Print / save PDF</button></html>`,'text/html');}
 };
 return controller;
}
