import {describe,it,expect} from 'vitest';
import {advanceQuarter,autoPlan,delegatePlan,plannedOptions,checksum,commitPlan,createCampaign,previewPlan,validatePlan,getView} from '../src/core/engine';
import {progressStudy,startStudy,studyCost} from '../src/core/clinical';
import {initiateCohort,remainingLifetime,scoreHealth,expectedQuarterGain,quarterlySurvival,projectLifetime} from '../src/core/health';
import {DEALS} from '../src/world/content';
const year=(s:ReturnType<typeof createCampaign>)=>{for(let i=0;i<4&&s.phase==='resolving';i++)s=advanceQuarter(s);return s;};
describe('campaign state and clinical clocks',()=>{
 it('has 24 planning years and exactly 96 resolved quarters, including 2050 Q4',()=>{
  let s=createCampaign();s.company.cash=10_000_000_000_000;const years:number[]=[];
  while(s.phase!=='ended'){years.push(s.year);s=year(commitPlan(s,[{type:'wait'},{type:'wait'}]));}
  expect(years).toEqual(Array.from({length:24},(_,i)=>2027+i));expect(s.tick).toBe(96);expect(s.year).toBe(2050);
  expect(Math.max(...s.cohorts.map(c=>c.start))).toBeLessThan(96);const closed=advanceQuarter(s);expect(closed).toEqual(s);
 });
 it('observation cannot begin before readiness and complete enrollment; every observation and review quarter is required',()=>{
  const s=createCampaign(),p=s.programs.find(p=>p.id==='immune-reset')!;startStudy(s,p,'narrow');const study=p.study!;
  progressStudy(s,p,10000,.4);expect(study.enrolled).toBe(0);expect(study.observation).toBe(0);
  progressStudy(s,p,10000,1);expect(study.enrolled).toBe(0);
  progressStudy(s,p,study.target-1,1);expect(study.enrolled).toBe(study.target-1);expect(study.observation).toBe(0);
  progressStudy(s,p,1,1);expect(study.observation).toBe(0);
  for(let i=0;i<study.observationRequired;i++){progressStudy(s,p,999,1);expect(p.study).not.toBeNull();}
  progressStudy(s,p,999,1);expect(p.study).not.toBeNull();progressStudy(s,p,999,1);expect(p.study).toBeNull();expect(p.stage).toBe('phase1');
 });
 it('pausing a study does not advance its clock',()=>{const s=createCampaign(),p=s.programs.find(p=>p.id==='immune-reset')!;startStudy(s,p,'broad');p.study!.paused=true;const copy=structuredClone(p.study);progressStudy(s,p,10000,1);expect(p.study).toEqual(copy);});
 it('requires exactly two commitments and validates their combined working capital',()=>{const s=createCampaign();expect(validatePlan(s,[{type:'wait'}]).valid).toBe(false);s.company.cash=150_000_000;const a={type:'build' as const,regionId:'pacific',family:'network' as const};expect(validatePlan(s,[a,a]).valid).toBe(false);expect(s.projects).toHaveLength(0);});
 it('construction changes actual capacity only after commissioning',()=>{let s=createCampaign();const capacity=s.regions[0].capacity;s=commitPlan(s,[{type:'build',regionId:s.regions[0].id,family:'network'},{type:'wait'}]);expect(s.regions[0].capacity).toBe(capacity);for(let i=0;i<3;i++)s=advanceQuarter(s);expect(s.regions[0].capacity).toBe(capacity);s=advanceQuarter(s);expect(s.regions[0].capacity).toBeGreaterThan(capacity*10);});
 it('the same seed and decisions reproduce cohorts, events, finances and checksums',()=>{let a=createCampaign('staggered',91),b=createCampaign('staggered',91);for(let i=0;i<6;i++){const pa=autoPlan(a),pb=autoPlan(b);expect(pa).toEqual(pb);a=year(commitPlan(a,pa));b=year(commitPlan(b,pb));}expect(checksum(a)).toBe(checksum(b));expect(a).toEqual(b);});
 it('previews expose no unobserved endpoints and do not mutate state',()=>{const a=createCampaign('convergence',17),b=createCampaign('convergence',781);const plan=[{type:'program' as const,programId:'immune-reset',operation:'start' as const},{type:'wait' as const}];const before=checksum(a);expect(previewPlan(a,plan)).toEqual(previewPlan(b,plan));expect(checksum(a)).toBe(before);expect(a.programs.find(p=>p.id==='immune-reset')!.study).toBeNull();});
});
describe('health accounting, capacity and control',()=>{
 it('counts distinct care initiations once and never credits idle capacity or financing',()=>{let s=createCampaign();const count=s.score.people;s=commitPlan(s,[{type:'build',regionId:'pacific',family:'network'},{type:'wait'}]);expect(s.score.people).toBe(count);s=year(s);expect(new Set(s.cohorts.map(c=>c.id)).size).toBe(s.cohorts.length);expect(s.score.people).toBe(s.regions.reduce((n,r)=>n+r.treated,0));expect(s.score.people).toBe(s.cohorts.reduce((n,c)=>n+c.count,0));});
 it('separates experienced and expected remaining years; better alternative care lowers increment',()=>{const s=createCampaign(),r=s.regions[0],p=s.programs[0];const c=initiateCohort(s,r,p,1000);s.cohorts=[c];s.score=scoreHealth(s);expect(s.score.expected).toBeCloseTo(s.score.experienced+s.score.remaining,7);const baseline=remainingLifetime(c,s);s.world.counterfactualAccess=.8;expect(remainingLifetime(c,s)).toBeLessThan(baseline);c.continuity=.3;expect(remainingLifetime(c,s)).toBeLessThan(baseline*.5);});
 it('additional harm reduces net expected health and preserves outside-care debit',()=>{const s=createCampaign(),c=initiateCohort(s,s.regions[0],s.programs[0],1000);s.cohorts=[c];const first=scoreHealth(s);s.outsideHarm=50;const second=scoreHealth(s);expect(second.expected).toBeCloseTo(first.expected-50);expect(second.experienced).toBeCloseTo(first.experienced-50);});
 it('2050 starts are credited but no 2051 start is permitted',()=>{let s=createCampaign();s.tick=92;s.year=2050;s.company.cash=100_000_000_000;s=year(commitPlan(s,[{type:'wait'},{type:'wait'}]));expect(s.cohorts.some(c=>c.start===95)).toBe(true);expect(s.cohorts.every(c=>c.start<96)).toBe(true);expect(validatePlan(s,[{type:'wait'},{type:'wait'}]).valid).toBe(false);});
 it('board control is checked immediately after a control transfer before any treatment resolves',()=>{const s=createCampaign();const d=DEALS.find(d=>d.id==='equity')!;const i=d.variants.findIndex(v=>v.founderSeats<3);const ended=commitPlan(s,[{type:'deal',dealId:d.id,variant:i},{type:'wait'}]);expect(ended.status).toBe('control-loss');expect(ended.phase).toBe('ended');expect(ended.score.people).toBe(0);});
 it('cash breach provides a genuine annual opportunity to cure',()=>{let s=createCampaign();s.company.cash=1;s=year(commitPlan(s,[{type:'wait'},{type:'wait'}]));expect(s.status).toBe('active');expect(s.phase).toBe('planning');expect(s.company.cureQuarter).toBeGreaterThan(s.tick);expect(s.regions.reduce((n,r)=>n+r.lastTreated,0)).toBe(0);});
});

describe('independent accounting fixtures',()=>{
 it('transfers a quarter from the tail without creating expected value at fixed assumptions',()=>{const s=createCampaign(),c=initiateCohort(s,s.regions[0],s.programs[0],10000);const before=projectLifetime(c,s,480);const earned=expectedQuarterGain(c,0,c.alive,s.world.counterfactualAccess);c.alive*=quarterlySurvival(c.age);s.tick=1;const after=projectLifetime(c,s,479);expect(after.value+earned).toBeCloseTo(before.value,8);});
 it('the computed tail bound contains the longer-horizon residual',()=>{const s=createCampaign(),c=initiateCohort(s,s.regions[0],s.programs[1],1000000);const short=projectLifetime(c,s,80),long=projectLifetime(c,s,480);expect(long.value-short.value).toBeGreaterThanOrEqual(0);expect(long.value-short.value).toBeLessThanOrEqual(short.tailBound);});
 it('shared slots close exactly and follow-up precedes new care',()=>{let s=createCampaign();s=year(commitPlan(s,[{type:'build',regionId:'pacific',family:'network'},{type:'wait'}]));for(const r of s.regions.filter(r=>r.queue)){const q=r.queue!;expect(q.rivals+q.followup+q.trials+q.care+q.idle).toBe(q.gross);expect(q.followup).toBe(Math.min(q.followupRequired,q.gross-q.rivals));}});
 it('a population mandate cannot mint guaranteed receipts without delivery',()=>{let s=createCampaign();s.year=2028;s.tick=4;s.regions[0].levels.clinic=0;const payer=DEALS.find(d=>d.id==='payer')!;s=commitPlan(s,[{type:'deal',dealId:payer.id,variant:2},{type:'wait'}]);s=advanceQuarter(s);expect(s.score.people).toBe(0);expect(s.company.lastRevenue).toBe(0);expect(s.company.lastExpenses).toBeGreaterThan(0);});
});

describe('policy and obligation regression fixtures',()=>{
 it('personal rollouts pay both levels and respect their captured target and six-quarter duration',()=>{let s=createCampaign();s.policy.stage='personal';s.company.cash=100000000000;const before=s.company.cash;s=commitPlan(s,[{type:'build',regionId:'pacific',family:'network'},{type:'wait'}]);expect(s.projects[0].targetLevel).toBe(2);expect(s.projects[0].remaining).toBe(6);expect(before-s.company.cash).toBe(140000000+287000000);s=year(s);expect(s.regions[0].levels.network).toBe(0);s=commitPlan(s,[{type:'wait'},{type:'wait'}]);s=advanceQuarter(s);s=advanceQuarter(s);expect(s.regions[0].levels.network).toBe(2);});
 it('broad evidence has a larger observed coverage gain and requires more participants and observation',()=>{const a=createCampaign(),b=createCampaign();const pa=a.programs[1],pb=b.programs[1];startStudy(a,pa,'narrow');startStudy(b,pb,'broad');expect(pb.study!.target).toBeGreaterThan(pa.study!.target);expect(pb.study!.observationRequired).toBeGreaterThan(pa.study!.observationRequired);for(let i=0;i<20;i++){progressStudy(a,pa,10000,1);progressStudy(b,pb,10000,1);}expect(pb.evidence).toBeGreaterThan(pa.evidence);expect(pb.benefit).toBe(pa.benefit);});
 it('payer receipts replace covered retail charges rather than billing the same starts twice',()=>{let s=createCampaign();s.year=2028;s.tick=4;s.company.cash=100000000000;const d=DEALS.find(d=>d.id==='payer')!,v=d.variants[0];s=advanceQuarter(commitPlan(s,[{type:'deal',dealId:d.id,variant:0},{type:'wait'}]));expect(s.score.people).toBeGreaterThan(0);const covered=s.cohorts.filter(c=>c.programId==='autoimmune-care').reduce((n,c)=>n+c.count,0),retail=s.cohorts.filter(c=>c.programId==='neuro-care').reduce((n,c)=>n+c.count*72000,0);expect(s.company.lastRevenue).toBe(Math.round(v.annualRevenue*covered/v.capacity+retail));});
 it('observed trial enrollment creates continuing follow-up without crediting the trial as care',()=>{let s=createCampaign();s=year(commitPlan(s,[{type:'program',programId:'immune-reset',operation:'start',package:'narrow'},{type:'build',regionId:'pacific',family:'network'}]));s=year(commitPlan(s,[{type:'wait'},{type:'wait'}]));const participants=Object.values(s.trialFollowup??{}).reduce((a,b)=>a+b,0);expect(participants).toBeGreaterThan(0);const people=s.score.people;s=commitPlan(s,[{type:'program',programId:'immune-reset',operation:'stop'},{type:'wait'}]);expect(Object.values(s.trialFollowup??{}).reduce((a,b)=>a+b,0)).toBe(participants);expect(s.score.people).toBe(people);});
});

describe('delegation boundaries',()=>{
 it('operational delegation never invents financing, policy change, or a new clinical program',()=>{const s=createCampaign();const actions=delegatePlan(s);expect(actions).toHaveLength(2);expect(actions.every(a=>a.type==='build'||a.type==='wait')).toBe(true);s.company.cash=1;expect(delegatePlan(s)).toEqual([{type:'wait'},{type:'wait'}]);expect(s.company.rounds).toHaveLength(0);});
});

describe('continuity after funding loss',()=>{
 it('insolvency revises only the future tail for uncertain portable handoff',()=>{let s=createCampaign();s.cohorts=[initiateCohort(s,s.regions[0],s.programs[1],10000)];s.score=scoreHealth(s);const before=structuredClone(s.score);s.company.cash=-1;s.company.cureQuarter=0;s=advanceQuarter(commitPlan(s,[{type:'wait'},{type:'wait'}]));expect(s.status).toBe('insolvent');expect(s.score.experienced).toBe(before.experienced);expect(s.score.remaining).toBeCloseTo(before.remaining*.55,7);expect(s.score.expected).toBeGreaterThan(0);expect(s.score.expected).toBeLessThan(before.expected);expect(s.events.at(-1)!.detail).toContain('55%');expect(scoreHealth(s)).toEqual(s.score);});
 it('a control transfer preserves the existing cohort score without a funding-loss haircut',()=>{let s=createCampaign();s.cohorts=[initiateCohort(s,s.regions[0],s.programs[1],10000)];s.score=scoreHealth(s);const before=structuredClone(s.score);const d=DEALS.find(d=>d.id==='equity')!,i=d.variants.findIndex(v=>v.founderSeats<3);s=commitPlan(s,[{type:'deal',dealId:d.id,variant:i},{type:'wait'}]);expect(s.status).toBe('control-loss');expect(s.score).toEqual(before);expect(scoreHealth(s)).toEqual(before);});
});

describe('program-linked therapy rights',()=>{
 it('a default license improves immune-reset readiness and future study cost without inventing evidence or approval',()=>{let s=createCampaign();s.year=2029;s.tick=8;const before=structuredClone(s.programs.find(p=>p.id==='immune-reset')!);const oldCost=studyCost(before,'narrow',s);s=commitPlan(s,[{type:'deal',dealId:'therapy',variant:0},{type:'wait'}]);const p=s.programs.find(p=>p.id==='immune-reset')!;expect(p.partnered).toBe(true);expect(p.readiness).toBeGreaterThan(before.readiness);expect(p.evidence).toBe(before.evidence);expect(p.stage).toBe(before.stage);expect(p.study).toBeNull();expect(studyCost(p,'narrow',s)).toBe(Math.round(oldCost*.8));expect(s.company.contracts.find(c=>c.family==='therapy')!.programId).toBe('immune-reset');expect(s.company.royalty).toBe(0);s.tick=28;expect(studyCost(p,'narrow',s)).toBe(oldCost);});
 it('an explicitly selected license applies only to that program and normal study packages retain the partnership',()=>{let s=createCampaign();s.year=2029;s.tick=8;const immune=structuredClone(s.programs.find(p=>p.id==='immune-reset')!);s=commitPlan(s,[{type:'deal',dealId:'therapy',variant:0,programId:'cancer-rna'},{type:'program',programId:'cancer-rna',operation:'start',package:'narrow'}]);const p=s.programs.find(p=>p.id==='cancer-rna')!;expect(p.partnered).toBe(true);expect(p.study!.budget).toBe(Math.round(90000000*.7*.8));expect(s.programs.find(p=>p.id==='immune-reset')).toEqual(immune);expect(s.company.contracts.find(c=>c.family==='therapy')!.programId).toBe('cancer-rna');});
 it('partner packages preserve their study price and scope their continuing royalty to the program',()=>{const s=createCampaign(),p=s.programs.find(p=>p.id==='immune-reset')!;const price=studyCost(p,'partner',s);startStudy(s,p,'partner');expect(p.study!.budget).toBe(price);expect(p.royalty).toBe(.025);expect(s.company.royalty).toBe(0);p.study=null;p.stage='phase1';startStudy(s,p,'narrow');expect(p.partnered).toBe(true);expect(p.royalty).toBe(.025);expect(s.company.royalty).toBe(0);});
 it('therapy royalties reduce only target-program retail receipts',()=>{const base=createCampaign();base.year=2029;base.tick=8;base.company.cash=100000000000;const ordinary=advanceQuarter(commitPlan(base,[{type:'wait'},{type:'wait'}]));const licensed=advanceQuarter(commitPlan(base,[{type:'deal',dealId:'therapy',variant:0,programId:'autoimmune-care'},{type:'wait'}]));expect(licensed.score.people).toBe(ordinary.score.people);const targetCount=licensed.cohorts.filter(c=>c.programId==='autoimmune-care').reduce((n,c)=>n+c.count,0);expect(ordinary.company.lastRevenue-licensed.company.lastRevenue).toBe(Math.round(targetCount*65000*.04));expect(licensed.programs.find(p=>p.id==='neuro-care')!.royalty??0).toBe(0);});
 it('payer-covered target care also pays its program royalty without retail double billing',()=>{const base=createCampaign();base.year=2029;base.tick=8;base.company.cash=100000000000;const ordinary=advanceQuarter(commitPlan(base,[{type:'deal',dealId:'payer',variant:0},{type:'wait'}]));const licensed=advanceQuarter(commitPlan(base,[{type:'deal',dealId:'therapy',variant:0,programId:'autoimmune-care'},{type:'deal',dealId:'payer',variant:0}]));const targetCount=licensed.cohorts.filter(c=>c.programId==='autoimmune-care').reduce((n,c)=>n+c.count,0);const payer=DEALS.find(d=>d.id==='payer')!.variants[0];const exactDifference=targetCount*payer.annualRevenue/payer.capacity*.04;expect(Math.abs((ordinary.company.lastRevenue-licensed.company.lastRevenue)-exactDifference)).toBeLessThanOrEqual(1);});
});


describe('funding cure execution',()=>{
 it('can actually close equity during the advertised cash cure period',()=>{let s=createCampaign();s.company.cash=1;s=year(commitPlan(s,[{type:'wait'},{type:'wait'}]));expect(s.company.cash).toBeLessThan(0);const plan=[{type:'deal' as const,dealId:'equity',variant:0},{type:'wait' as const}];expect(validatePlan(s,plan).valid).toBe(true);s=commitPlan(s,plan);expect(s.company.cash).toBeGreaterThan(0);expect(s.company.cureQuarter).toBeNull();expect(s.status).toBe('active');});
});


describe('payer working capital and scope',()=>{
 it('prepaid care adds actual starts when capacity is funded but care working capital is scarce',()=>{const base=createCampaign();base.year=2028;base.tick=4;base.company.cash=11000000;const r=base.regions[0];r.levels={clinic:2,diagnostics:2,manufacturing:2,evidence:2,followup:2,network:5};r.siteCount=25000;r.capacity=2500000;const ordinary=advanceQuarter(commitPlan(base,[{type:'wait'},{type:'wait'}]));const contracted=advanceQuarter(commitPlan(base,[{type:'deal',dealId:'payer',variant:1},{type:'wait'}]));expect(contracted.score.people).toBeGreaterThan(ordinary.score.people);expect(contracted.company.contracts[0].programId).toBe('autoimmune-care');expect(contracted.company.credits).toBe(0);expect(contracted.company.totalRevenue).toBe(contracted.company.lastRevenue);});
 it('cannot spend an undelivered payer allowance on a building or receive it as cash at signing',()=>{const base=createCampaign();base.year=2028;base.tick=4;base.company.cash=11000000;const plan=[{type:'deal' as const,dealId:'payer',variant:2},{type:'build' as const,regionId:'pacific',family:'network' as const}];expect(validatePlan(base,plan).valid).toBe(false);const signed=commitPlan(base,[plan[0],{type:'wait'}]);expect(signed.company.cash).toBe(base.company.cash);});
});


it('a queued financing unlocks affordable second commitments without changing authoritative cash',()=>{const s=createCampaign();s.company.cash=1;const before=checksum(s);const action={type:'deal' as const,dealId:'equity',variant:0};const choice=plannedOptions(s,[action]).find(o=>o.id==='build:pacific:network')!;expect(choice.available).toBe(true);expect(validatePlan(s,[action,choice.action]).valid).toBe(true);expect(checksum(s)).toBe(before);expect(plannedOptions(s,[]).find(o=>o.id===choice.id)!.available).toBe(false);});

it('a pending control transfer still allows the hold needed to commit and receive the ending',()=>{const s=createCampaign();expect(plannedOptions(s,[{type:'deal',dealId:'equity',variant:2}]).find(o=>o.action.type==='wait')!.available).toBe(true);});

it('queued institutional decisions preserve their original label and cost while changing remaining choices',()=>{const s=createCampaign();s.policy.stage='platform';s.policy.qualified=true;s.world.biology=2;s.world.modelVersion=4;s.programs[1].evidence=.75;s.company.cash=10000000000;const before=plannedOptions(s,[]).find(o=>o.id==='policy:platform')!;expect(before.available).toBe(true);const after=plannedOptions(s,[before.action]);expect(after.find(o=>o.id===before.id)!.label).toBe(before.label);expect(after.find(o=>o.id===before.id)!.cost).toBe(before.cost);expect(after.find(o=>o.id==='policy:recognition')!.available).toBe(false);expect(after.find(o=>o.id==='build:pacific:network')!.duration).toContain('6');});

it('hold remains repeatable in both annual slots',()=>{const s=createCampaign();expect(plannedOptions(s,[{type:'wait'}]).find(o=>o.id==='wait')!.available).toBe(true);expect(validatePlan(s,[{type:'wait'},{type:'wait'}]).valid).toBe(true);});

it('the combined plan explains the actual personal rollout scope and clock',()=>{const s=createCampaign();s.policy.stage='platform';s.world.biology=2;s.world.modelVersion=4;s.programs[1].evidence=.75;s.company.cash=10000000000;const preview=previewPlan(s,[{type:'policy',operation:'platform'},{type:'build',regionId:'pacific',family:'network'}]);expect(preview.valid).toBe(true);expect(preview.summary[1]).toContain('6 quarters at network level 2');});


describe('cycle two decision clarity',()=>{
 it('previews one paid commitment without enabling annual commit or mutating state',()=>{const s=createCampaign(),before=checksum(s);const preview=previewPlan(s,[{type:'build',regionId:'pacific',family:'clinic'}]);expect(preview.valid).toBe(false);expect(preview.cost).toBeGreaterThan(0);expect(preview.cashAfter).toBe(s.company.cash-preview.cost);expect(preview.summary).toHaveLength(1);expect(checksum(s)).toBe(before);});
 it('study cards match the package and institutional observation clocks',()=>{const s=createCampaign(),p=s.programs.find(p=>p.id==='immune-reset')!;p.stage='phase1';let card=getView(s).options.find(o=>o.id==='study:immune-reset:broad')!;expect(card.duration).toContain('7 observation');expect(card.duration).toContain('2 review');s.policy.stage='personal';p.platformScope=true;card=getView(s).options.find(o=>o.id==='study:immune-reset:narrow')!;expect(card.duration).toContain('3 observation');expect(card.duration).toContain('1 review');startStudy(s,p,'narrow');expect(p.study!.observationRequired).toBe(3);});
 it('endings explain the shortfall and never suggest another actionable commitment',()=>{const s=createCampaign();s.phase='ended';s.status='partial';s.score.expected=937800000;const view=getView(s);expect(view.guidance).toContain('62.2M');expect(view.guidance).toContain('short');expect(view.options.every(o=>!o.available&&o.reason.startsWith('Campaign complete'))).toBe(true);});
});


describe('cycle three operational delegation',()=>{
 it('repairs an affordable follow-up bottleneck before discretionary work, using an ordinary commitment',()=>{const s=createCampaign();s.year=2036;s.tick=36;s.company.cash=5500000000;s.company.lastExpenses=300000000;s.company.lastRevenue=200000000;const r=s.regions[0];r.levels.network=4;r.levels.clinic=2;r.bottleneck='followup';r.capacity=480000;r.waiting=1000000;const before=checksum(s),actions=delegatePlan(s);expect(actions[0]).toEqual({type:'build',regionId:'pacific',family:'followup'});expect(validatePlan(s,actions).valid).toBe(true);expect(actions.every(a=>a.type==='build'||a.type==='wait')).toBe(true);expect(checksum(s)).toBe(before);const committed=commitPlan(s,actions);expect(committed.company.cash).toBeLessThan(s.company.cash);expect(committed.projects.some(p=>p.family==='followup')).toBe(true);});
 it('keeps the reserve instead of buying an unaffordable continuity upgrade or inventing funding',()=>{const s=createCampaign();s.company.cash=1000000;s.regions[0].bottleneck='followup';expect(delegatePlan(s)).toEqual([{type:'wait'},{type:'wait'}]);});
 it('prices a chosen advocacy budget exactly and preserves it in the queued card',()=>{const s=createCampaign();const action:import('../src/core/types').Action={type:'policy',operation:'lobby',budget:360000000};const preview=previewPlan(s,[action,{type:'wait'}]);expect(preview.cost).toBe(360000000);expect(preview.cashAfter).toBe(s.company.cash-360000000);const card=plannedOptions(s,[action]).find(o=>o.id==='policy:lobby')!;expect(card.cost).toBe(360000000);expect(card.label).toContain('$3.6M');});
 it('flags a conditional operating funding need in the annual plan',()=>{const s=createCampaign();s.company.cash=10000000;const preview=previewPlan(s,[{type:'wait'},{type:'wait'}]);expect(preview.summary.some(t=>t.includes('funding need'))).toBe(true);});
});


it('keeps immediate commitment cash separate from later operating cash in the decision trace',()=>{const s=createCampaign();const committed=commitPlan(s,[{type:'build',regionId:'pacific',family:'clinic'},{type:'wait'}]);const paid=committed.trace[0].cashAfterCommit;const resolved=advanceQuarter(committed);expect(resolved.trace[0].cashAfterCommit).toBe(paid);expect(resolved.trace[0].cashAfter).toBe(resolved.company.cash);expect(resolved.trace[0].cashAfter).not.toBe(paid);});


describe('conservative expansion under delegation',()=>{
 it.each(['demand','cash','permission'] as const)('does not buy throughput when %s is the actual constraint',(constraint)=>{const s=createCampaign();s.year=2049;s.tick=88;s.company.cash=10000000000000;s.regions[0].bottleneck=constraint;s.regions[0].waiting=10000000;const before=checksum(s);const actions=delegatePlan(s);expect(actions).toEqual([{type:'wait'},{type:'wait'}]);expect(checksum(s)).toBe(before);expect(validatePlan(s,[{type:'build',regionId:'pacific',family:'clinic'},{type:'wait'}]).valid).toBe(true);});
 it('continues approved clinical work even when additional commercial capacity is not needed',()=>{const s=createCampaign();s.year=2035;s.tick=32;s.company.cash=10000000000;s.regions[0].bottleneck='demand';const p=s.programs.find(p=>p.id==='immune-reset')!;p.stage='phase1';p.evidence=.2;const actions=delegatePlan(s);expect(actions.some(a=>a.type==='program'&&a.operation==='advance')).toBe(true);expect(actions.some(a=>a.type==='build')).toBe(false);expect(validatePlan(s,actions).valid).toBe(true);});
});


it('waits for funded platform qualification before automatically starting a redundant phase3',()=>{const s=createCampaign();s.year=2038;s.tick=44;s.company.cash=10000000000;s.regions[0].bottleneck='demand';const p=s.programs.find(p=>p.id==='immune-reset')!;p.stage='phase2';p.evidence=.6;s.policy.stage='implementing';s.projects=[{id:'funded-platform',name:'Platform',kind:'platform',remaining:2,started:40,cost:200000000}];const actions=delegatePlan(s);expect(actions).toEqual([{type:'wait'},{type:'wait'}]);expect(validatePlan(s,[{type:'program',programId:p.id,operation:'advance',package:'narrow'},{type:'wait'}]).valid).toBe(true);let after=commitPlan(s,actions);after=advanceQuarter(advanceQuarter(after));expect(after.programs.find(p=>p.id==='immune-reset')!.stage).toBe('platform');expect(after.programs.find(p=>p.id==='immune-reset')!.study).toBeNull();});
