import {describe,it,expect} from 'vitest';
import {createCampaign,commitPlan,checksum,validatePlan} from '../src/network/engine';
import {replay,writeSave} from '../src/network/storage';
import {advanceTour,TOUR_STAGES,tourStageAt,TOUR_SEED,TOUR_SCENARIO} from '../src/network/tour';

describe('conservative investor tour',()=>{
 it('provides six continuous planning stops and a pinned introductory campaign',()=>{expect(TOUR_STAGES.map(s=>s.tick)).toEqual([0,12,28,48,72,96]);expect(tourStageAt(30).id).toBe('clinical');expect(TOUR_SEED).toBe(2027);expect(TOUR_SCENARIO).toBe('convergence');});
 it('is pure, deterministic and preserves the player’s prior decisions',()=>{const input=commitPlan(createCampaign(),[{type:'raise',amount:300000000,terms:'protected'},{type:'expand',siteId:'riverside'}]);const before=checksum(input),a=advanceTour(input),b=advanceTour(input);expect(checksum(input)).toBe(before);expect(a).toEqual(b);expect(a.state.commands[0]).toEqual(input.commands[0]);expect(a.state.tick).toBeGreaterThan(input.tick);expect(a.stopReason.kind).toBe('world');});
 it('uses legal ordinary commands whose complete campaign replays exactly',()=>{const input=commitPlan(createCampaign(),[{type:'raise',amount:300000000,terms:'protected'}]);const result=advanceTour(input);let s=input;for(const q of result.delegatedActions){expect(q.tick).toBe(s.tick);expect(validatePlan(s,q.actions).valid).toBe(true);expect(q.actions.every(a=>a.type==='expand')).toBe(true);s=commitPlan(s,q.actions);}expect(checksum(s)).toBe(checksum(result.state));expect(checksum(replay(writeSave(result.state)))).toBe(checksum(result.state));});
 it('interrupts before funding risk and never creates rescue capital',()=>{const state=createCampaign();state.company.cash=1000000;const before=checksum(state),result=advanceTour(state);expect(result.stopReason.kind).toBe('risk');expect(result.delegatedActions).toEqual([]);expect(checksum(result.state)).toBe(before);expect(result.state.company.rounds).toEqual(state.company.rounds);});
 it('returns a funding cure to the player without advancing or selling',()=>{const state=createCampaign();state.company.cash=-1;state.cureUntil=1;const result=advanceTour(state);expect(result.stopReason.kind).toBe('risk');expect(result.state.tick).toBe(0);expect(result.delegatedActions).toHaveLength(0);});
 it('stops at a new AI generation without automatically adopting it',()=>{const state=createCampaign();state.company.cash=10000000000;const current=state.programs.map(p=>p.candidate.generation);const result=advanceTour(state);expect(result.stopReason.kind).toBe('world');expect(result.state.programs.map(p=>p.candidate.generation)).toEqual(current);expect(result.state.world.generation).toBeGreaterThan(state.world.generation);expect(result.delegatedActions.length).toBeLessThanOrEqual(12);});
 it('never turns a failure or a completed partial campaign into success',()=>{for(const status of ['insolvent','control-loss','partial'] as const){const state=createCampaign();state.status=status;state.tick=status==='partial'?96:4;const result=advanceTour(state);expect(result.state.status).toBe(status);expect(result.state.health.expected).toBe(0);expect(result.stopReason.kind).toBe('ended');expect(result.delegatedActions).toHaveLength(0);}});
 it('allows committed study work to finish but does not initiate the next phase',()=>{let state=createCampaign();state.company.cash=10000000000;state.partnerships.push('manufacturer');state.facilities.find(f=>f.id==='riverside')!.trialTeam=true;state=commitPlan(state,[{type:'study',programId:'immune-reset',siteId:'riverside',package:'focused'}]);let result=advanceTour(state);for(let i=0;i<5&&result.stopReason.kind==='world';i++)result=advanceTour(result.state);expect(result.stopReason.kind).toBe('clinical');const p=result.state.programs.find(p=>p.id==='immune-reset')!;expect(p.study===null||p.study.failed).toBe(true);expect(result.delegatedActions.flatMap(q=>q.actions).some(a=>a.type==='study')).toBe(false);});
 it('does not repeatedly expand when compatible upstream capacity cannot improve care',()=>{const state=createCampaign();state.company.cash=10000000000;state.facilities.find(f=>f.id==='supplier')!.capacity=80;const result=advanceTour(state);expect(result.delegatedActions.flatMap(q=>q.actions)).toHaveLength(0);});
});

it('names a current follow-up shortage and resumes after support is restored despite historical harm',()=>{
 const state=commitPlan(createCampaign(),[{type:'raise',amount:300000000,terms:'protected'}]);
 const site=state.facilities.find(f=>f.id==='riverside')!;state.cohorts[0].continuity=.5;site.capacity=1;site.employees=0;
 const blocked=advanceTour(state);expect(blocked.stopReason.title).toBe('Continuing care needs attention');expect(blocked.stopReason.detail).toContain('Riverside');expect(blocked.stopReason.detail).toContain('visits needed');expect(blocked.state.tick).toBe(state.tick);
 site.capacity=120;site.employees=8;const resumed=advanceTour(state);expect(resumed.state.tick).toBeGreaterThan(state.tick);expect(resumed.delegatedActions.length).toBeGreaterThan(0);expect(state.cohorts[0].continuity).toBe(.5);
});
