import {useEffect,useMemo,useState} from 'react';
import type {Facility,View} from './types';

export const facilityNames:Record<Facility['kind'],string>={community:'Community',clinic:'Treatment clinic',hospital:'Specialist hospital',lab:'Testing laboratory',factory:'Therapy factory'};
const crop:Record<Facility['kind'],[number,number]>={factory:[0,0],clinic:[512,0],hospital:[1024,0],lab:[0,512],community:[0,0]};
function FacilityArt({facility}:{facility:Facility}){
  if(facility.kind==='community')return <g className="community-art"><ellipse cx="0" cy="20" rx="40" ry="16" fill="#b9cfb9"/><path d="M-34 12V-5L-16-16 2-5V15L-16 27Z" fill="#e9d9bc"/><path d="M2 15V-5L-16-16V6Z" fill="#c8b28c"/><path d="M-36-5L-16-20 5-5-15 9Z" fill="#6f8a79"/><path d="M7 20V0L24-10 39 0V21L24 29Z" fill="#e6d8c0"/><path d="M4 0L24-14 42 0 23 13Z" fill="#bd9b79"/><path d="M-22 16V6L-14 10V21M19 23V14L25 18V27" fill="#748477"/><circle cx="-40" cy="11" r="9" fill="#829f7f"/><circle cx="45" cy="11" r="9" fill="#94ae89"/></g>;
  const c=facility.delivery==='local'?[512,512]:facility.delivery==='home'||facility.delivery==='wearable'?[1024,512]:crop[facility.kind];
  return <foreignObject x="-52" y="-61" width="104" height="104" aria-hidden="true" style={{pointerEvents:'none'}}><div style={{width:104,height:104,backgroundImage:'url(/network-art/facilities.png)',backgroundSize:'300% 200%',backgroundPosition:`${c[0]/1024*100}% ${c[1]/512*100}%`,mixBlendMode:'multiply'}}/></foreignObject>;
}
export default function Board({view,selected,onSelect,pendingSites=[]}:{view:View;selected:string;onSelect:(id:string)=>void;pendingSites?:string[]}){
  const [zoom,setZoom]=useState(1);const [pan,setPan]=useState({x:0,y:0});
  const allFacilities=view.state.facilities;const selectedRegion=allFacilities.find(f=>f.id===selected)?.region??0;const [region,setRegion]=useState(selectedRegion);useEffect(()=>setRegion(selectedRegion),[selectedRegion]);const availableRegions=view.state.regions.filter(r=>allFacilities.some(f=>f.region===r.id));
  const networks=allFacilities.filter(f=>f.region===region&&f.id.startsWith('network-'));
  const networkOf=(id:string)=>networks.find(n=>id===n.id||['supply-','tests-','people-'].some(prefix=>id===prefix+n.id))?.id??'original';
  const networkId=networkOf(selected);const hasOriginal=allFacilities.some(f=>f.region===region&&networkOf(f.id)==='original');
  const facilities=allFacilities.filter(f=>f.region===region&&networkOf(f.id)===networkId);const visibleIds=new Set(facilities.map(f=>f.id));const visibleLinks=view.state.links.filter(l=>visibleIds.has(l.from)&&visibleIds.has(l.to));const regionInfo=view.state.regions.find(r=>r.id===region);
  const points=useMemo(()=>{const xs=facilities.map(f=>f.x),ys=facilities.map(f=>f.y);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);return new Map(facilities.map(f=>[f.id,{x:105+(f.x-minX)/Math.max(1,maxX-minX)*790,y:200+(f.y-minY)/Math.max(1,maxY-minY)*310}]))},[facilities]);
  const selectedFacility=facilities.find(f=>f.id===selected);
  const activeLinks=view.state.links.filter(l=>!selectedFacility||l.from===selected||l.to===selected);
  return <div className="network-board">
    <div className="board-caption"><label className="region-picker"><span>YOUR DELIVERY NETWORK</span><select aria-label="Map region" value={region} onChange={e=>{const next=Number(e.target.value);setRegion(next);setZoom(1);setPan({x:0,y:0});const f=allFacilities.find(f=>f.region===next&&(f.kind==='clinic'||f.kind==='hospital')&&(f.owner==='db'||f.owner==='partner'))||allFacilities.find(f=>f.region===next);if(f)onSelect(f.id)}}>{availableRegions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><h2>Connect what medicine needs.</h2><p>{new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(regionInfo?.waiting??0)} waiting · Select a place to see its next move.</p></div>
    {networks.length+(hasOriginal?1:0)>1&&<label className="network-picker">Network in this region<select aria-label="Network in this region" value={networkId} onChange={e=>{setZoom(1);setPan({x:0,y:0});onSelect(e.target.value==='original'?'riverside':e.target.value)}}>{hasOriginal&&<option value="original">Original coastal network</option>}{networks.map(n=><option key={n.id} value={n.id}>{n.name} · {n.capacity.toLocaleString()} capacity · {n.status}</option>)}</select></label>}
    <div className="map-tools" aria-label="Map controls"><button onClick={()=>setZoom(z=>Math.min(1.7,z+.15))} aria-label="Zoom in">+</button><button onClick={()=>setZoom(z=>Math.max(.8,z-.15))} aria-label="Zoom out">−</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0})}} aria-label="Reset map">↺</button></div>
    <svg className="network-svg" viewBox="0 0 1000 665" role="group" aria-label="Healthcare delivery network. Select facilities to inspect and plan." onPointerDown={e=>{if(e.button===0&&!(e.target as Element).closest('.facility-node')){const start={...pan};const el=e.currentTarget;const factor=1000/el.getBoundingClientRect().width;el.setPointerCapture(e.pointerId);const move=(p:PointerEvent)=>setPan({x:start.x+ (p.clientX-e.clientX)*factor,y:start.y+(p.clientY-e.clientY)*factor});const end=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',end)}}}>
      <defs><pattern id="map-grain" width="23" height="23" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r=".65" fill="#346e62" opacity=".12"/></pattern><filter id="building-shadow"><feDropShadow dx="0" dy="7" stdDeviation="7" floodColor="#173e35" floodOpacity=".13"/></filter><marker id="arrow-medicine" markerWidth="7" markerHeight="7" refX="5" refY="3" orient="auto"><path d="M0 0L6 3 0 6" fill="none" stroke="#b99332"/></marker><marker id="arrow-tests" markerWidth="7" markerHeight="7" refX="5" refY="3" orient="auto"><path d="M0 0L6 3 0 6" fill="none" stroke="#388b96"/></marker><marker id="arrow-patients" markerWidth="7" markerHeight="7" refX="5" refY="3" orient="auto"><path d="M0 0L6 3 0 6" fill="none" stroke="#b97059"/></marker></defs>
      <rect width="1000" height="665" fill="#edf0df"/><path d="M0 0H1000V60C860 10 788 76 735 132S690 266 786 345 844 492 745 665H0Z" fill="#f4f1e6"/><path d="M1000 77C851 18 806 85 767 147S720 259 808 333 876 495 782 665H1000Z" fill="#d3e7e3"/><path d="M1000 96C877 44 829 94 790 150S742 250 830 328 902 505 805 665" fill="none" stroke="#bad7d1" strokeWidth="2"/><path d="M-20 325C165 257 292 389 494 329S706 172 748-25M270 685C379 506 469 493 553 534S714 585 841 520" fill="none" stroke="#e5e1cf" strokeWidth="25"/><path d="M-20 325C165 257 292 389 494 329S706 172 748-25M270 685C379 506 469 493 553 534S714 585 841 520" fill="none" stroke="#fcfaf3" strokeWidth="2" strokeDasharray="7 5"/><rect width="1000" height="665" fill="url(#map-grain)"/>
      <g className="map-topography" fill="none" stroke="#d4deca" strokeWidth="1"><path d="M-20 184C30 84 211 29 272 64S346 168 272 191 120 137 84 229-30 304-20 184Z"/><path d="M-16 178C47 108 205 53 246 82S301 151 251 163 118 156 72 225"/><path d="M667 488C704 418 668 377 595 400S519 510 576 570 687 562 667 488Z"/><path d="M646 486C679 436 647 409 605 425S549 502 588 543 664 539 646 486Z"/></g>
      <g transform={`translate(${500+pan.x} ${330+pan.y}) scale(${zoom}) translate(-500 -330)`}>
        {new Set(facilities.map(f=>f.region)).size>1&&view.state.regions.map((region,i)=>{const members=facilities.filter(f=>f.region===region.id),ps=members.map(f=>points.get(f.id)!);if(!ps.length)return null;return <text key={region.id} x={Math.min(...ps.map(p=>p.x))-50} y={Math.min(...ps.map(p=>p.y))-57} className="map-region">{region.name.toUpperCase()} <tspan className="map-region-index">0{i+1}</tspan></text>})}
        {visibleLinks.map(link=>{const a=points.get(link.from),b=points.get(link.to);if(!a||!b)return null;const d=`M${a.x} ${a.y+10}Q${(a.x+b.x)/2} ${(a.y+b.y)/2-24} ${b.x} ${b.y+10}`;const highlight=activeLinks.includes(link);return <g key={link.id} className={`network-link ${link.kind} ${link.active?'active':''} ${highlight?'emphasized':'subdued'}`}><path d={d} className="link-shadow"/><path d={d} markerEnd={`url(#arrow-${link.kind})`}><title>{link.kind}: {link.lastFlow.toLocaleString()} used / {link.capacity.toLocaleString()} capacity</title></path>{highlight&&link.lastFlow>0&&<circle r="3.5" className="flow-particle"><animateMotion dur={`${3+(link.lastFlow%3)}s`} repeatCount="indefinite" path={d}/></circle>}</g>})}
        {facilities.map(f=>{const p=points.get(f.id)!;const isSelected=f.id===selected,planned=pendingSites.includes(f.id);return <g key={f.id} transform={`translate(${p.x} ${p.y})`} role="button" tabIndex={0} aria-label={`${f.name}, ${facilityNames[f.kind]}, ${f.owner==='db'?'owned by Digital Biologics':f.owner==='available'?'available site':f.owner}, ${f.status}`} aria-pressed={isSelected} onClick={()=>onSelect(f.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(f.id)}}} className={`facility-node ${isSelected?'selected':''} ${f.status} ${f.owner==='available'?'available':''}`}>
          <rect x="-86" y="-65" width="172" height="151" fill="transparent" pointerEvents="all"/><ellipse className="node-ring" cx="0" cy="16" rx="55" ry="31"/><g filter="url(#building-shadow)" style={{mixBlendMode:'multiply'}}><FacilityArt facility={f}/></g>
          {f.owner==='db'&&<g transform="translate(34 -40)"><circle r="11" fill="#145a4a"/><text y="3" textAnchor="middle" fill="white" fontSize="7" fontWeight="700">DB</text></g>}
          {(f.trialTeam||f.delivery!=='clinic')&&<g transform="translate(-40 -40)"><circle r="12" fill="#e8c974"/><text y="4" textAnchor="middle" fill="#435146" fontSize="12">{f.delivery==='wearable'?'⌁':f.delivery==='home'?'⌂':f.delivery==='local'?'⚙':'+'}</text></g>}
          {(planned||f.status==='building')&&<g transform="translate(0 -65)"><rect x="-37" y="-12" width="74" height="20" rx="10" fill="#ebc963"/><text y="2" textAnchor="middle" fontSize="10" fill="#51451c">{planned?'PLANNED':'BUILDING'}</text></g>}
          <rect className="node-label-bg" x="-86" y="44" width="172" height="39" rx="7"/><text textAnchor="middle" y="59" className="node-name">{f.name.length>26?f.name.slice(0,24)+'…':f.name}</text><text textAnchor="middle" y="74" className="node-kind">{f.owner==='available'?'Build or partner here':f.kind==='community'?'People waiting for care':f.trialTeam?'Treatment + clinical trials':facilityNames[f.kind]}</text>
        </g>})}
      </g>
      <text x="897" y="579" className="water-label" transform="rotate(-70 897 579)">THE OPEN COAST</text>
    </svg>
    <div className="map-legend"><span><i className="medicine"/>Medicines</span><span><i className="tests"/>Tests</span><span><i className="patients"/>Patients</span><span className="map-legend-note">Lines show real capacity, not bonus points.</span></div>
  </div>
}
